(function(){
const style=document.createElement('style');style.textContent=`#rrv36{position:fixed;right:14px;top:90px;width:310px;max-height:80vh;overflow:auto;background:rgba(18,22,30,.96);color:#eee;z-index:99999;padding:14px;border-radius:12px;font:13px Arial;box-shadow:0 8px 30px #0008}#rrv36 h3{margin:0 0 8px}#rrv36 button,#rrv36 select,#rrv36 input{margin:3px;padding:6px;border-radius:6px;border:1px solid #555;background:#252b36;color:#fff}#rrv36 button{cursor:pointer}#rrv36 .row{display:flex;gap:4px;align-items:center;flex-wrap:wrap}.rrv36-card{border:1px solid #444;padding:7px;margin:6px 0;border-radius:8px}`;document.head.appendChild(style);
const p=document.createElement('div');p.id='rrv36';p.innerHTML=`<h3>V36 • Production Handoff</h3><div class="row"><button id="r36bom">Generate BOM</button><button id="r36csv">Export CSV</button><button id="r36json">Export JSON</button></div><div class="row"><button id="r36spec">Print Specs</button><button id="r36clear">Clear Report</button></div><div class="rrv36-card"><b>Assembly / Installation</b><div class="row"><button id="r36base">Base Run</button><button id="r36wall">Wall Run</button><button id="r36tall">Tall Run</button></div><div class="row"><label>Gap mm <input id="r36gap" type="number" value="2" min="0" style="width:65px"></label><button id="r36gapset">Apply Gap</button></div></div><div id="r36out"></div>`;document.body.appendChild(p);
function objs(){return (window.objects||[]).filter(o=>o&&o.userData!==undefined)}
function dims(o){let d=o.userData||{};return {w:Number(d.w||0),h:Number(d.h||0),depth:Number(d.d||d.depth||0)}}
function rows(){return objs().map((o,i)=>{let d=dims(o),u=o.userData||{};return {no:i+1,name:u.type||u.kind||'Unit',w:d.w,h:d.h,d:d.depth,x:+(o.position?.x||0).toFixed(3),y:+(o.position?.y||0).toFixed(3),z:+(o.position?.z||0).toFixed(3),finish:u.finish||u.material||'',handle:u.handle||''}})}
function report(){let r=rows();document.getElementById('r36out').innerHTML=`<b>${r.length} objects</b>`+r.slice(0,80).map(x=>`<div class="rrv36-card">${x.no}. ${x.name} — ${x.w}×${x.h}×${x.d} mm<br>Pos ${x.x}, ${x.y}, ${x.z}${x.finish?' • '+x.finish:''}${x.handle?' • '+x.handle:''}</div>`).join('')}
function dl(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.getElementById('r36bom').onclick=report;
document.getElementById('r36json').onclick=()=>dl('RR-V36-specifications.json',JSON.stringify({version:'V36',objects:rows()},null,2),'application/json');
document.getElementById('r36csv').onclick=()=>{let r=rows(),head='No,Name,W,H,D,X,Y,Z,Finish,Handle\n';let s=head+r.map(x=>[x.no,x.name,x.w,x.h,x.d,x.x,x.y,x.z,x.finish,x.handle].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');dl('RR-V36-BOM.csv',s,'text/csv')};
document.getElementById('r36spec').onclick=()=>{report();setTimeout(()=>window.print(),100)};
document.getElementById('r36clear').onclick=()=>document.getElementById('r36out').innerHTML='';
function setRun(which){let r=rows();if(!r.length)return alert('Select/add cabinets first.');let target=r.map((x,i)=>objs()[i]);let x=0,z=0;if(which==='base'){target=target.filter(o=>/base|drawer|basket|sink|hob/i.test(o.userData?.type||''));}else if(which==='wall'){target=target.filter(o=>/wall|glass|shelf/i.test(o.userData?.type||''));}else target=target.filter(o=>/tall|pantry/i.test(o.userData?.type||''));if(!target.length) target=objs();target.forEach((o,i)=>{let d=dims(o);o.position.x=i*(d.w/1000+.01);});report()}
document.getElementById('r36base').onclick=()=>setRun('base');document.getElementById('r36wall').onclick=()=>setRun('wall');document.getElementById('r36tall').onclick=()=>setRun('tall');
document.getElementById('r36gapset').onclick=()=>{let g=Number(document.getElementById('r36gap').value||0)/1000,a=objs();let x=0;a.forEach(o=>{let d=dims(o);o.position.x=x;x+=d.w/1000+g});report()};
})();
