(function(){
const css=document.createElement('style');css.textContent=`#rrv37{position:fixed;right:14px;bottom:14px;width:330px;max-height:72vh;overflow:auto;background:rgba(12,16,23,.98);color:#f5f7fa;z-index:100000;padding:14px;border:1px solid #4b5563;border-radius:14px;font:12px Arial;box-shadow:0 12px 40px #0009}#rrv37 h3{margin:0 0 6px;font-size:16px}.r37row{display:flex;gap:5px;flex-wrap:wrap;margin:5px 0}.r37row>*{flex:1}.r37btn,.r37in,.r37sel{box-sizing:border-box;width:100%;padding:7px;border-radius:7px;border:1px solid #4b5563;background:#222a35;color:#fff}.r37card{padding:8px;margin:6px 0;border:1px solid #374151;border-radius:8px;background:#151b24}.r37small{font-size:10px;opacity:.72}.r37table{width:100%;border-collapse:collapse;font-size:9px}.r37table th,.r37table td{border-bottom:1px solid #303846;padding:4px;text-align:left}`;document.head.appendChild(css);
const p=document.createElement('div');p.id='rrv37';p.innerHTML=`<h3>V37 • Manufacturing & Installation</h3><div class="r37small">Generate a practical panel/cabinet cut-list from the current 3D scene.</div><div class="r37row"><button class="r37btn" id="r37gen">Generate Cut List</button><button class="r37btn" id="r37csv">Export CSV</button></div><div class="r37row"><button class="r37btn" id="r37print">Print Cut List</button><button class="r37btn" id="r37clear">Clear</button></div><div class="r37row"><label class="r37small">Carcass thickness mm<input class="r37in" id="r37thick" type="number" value="18" min="1"></label><label class="r37small">Back thickness mm<input class="r37in" id="r37back" type="number" value="6" min="1"></label></div><div class="r37row"><label class="r37small">Shutter reveal mm<input class="r37in" id="r37reveal" type="number" value="2" min="0"></label></div><div id="r37out"></div>`;document.body.appendChild(p);
function objs(){return (window.objects||[]).filter(o=>o&&o.isObject3D)}
function dim(o){let u=o.userData||{};let w=Number(u.w||0),h=Number(u.h||0),d=Number(u.d||u.depth||0);if(!w||!h||!d){try{let b=new THREE.Box3().setFromObject(o),s=new THREE.Vector3();b.getSize(s);w=Math.round(s.x*1000);h=Math.round(s.y*1000);d=Math.round(s.z*1000)}catch(e){}}return {w:Math.round(w),h:Math.round(h),d:Math.round(d)}}
function kind(o){let u=o.userData||{};return String(u.type||u.kind||o.name||'Cabinet')}
function cutFor(o,i){let d=dim(o),k=kind(o).toLowerCase(),t=+document.getElementById('r37thick').value||18,b=+document.getElementById('r37back').value||6,r=+document.getElementById('r37reveal').value||2;let parts=[];let innerW=Math.max(0,d.w-2*t);let innerH=Math.max(0,d.h-2*t);let carcD=Math.max(0,d.d-b);parts.push(['Side L',d.h,carcD,t]);parts.push(['Side R',d.h,carcD,t]);parts.push(['Top',innerW,carcD,t]);parts.push(['Bottom',innerW,carcD,t]);parts.push(['Back',Math.max(0,d.w-2*t),d.h,b]);if(!/open|shelf|panel|worktop|light|door|window|appliance|sink|hob|chimney|fridge|oven|dishwasher|dustbin/i.test(k))parts.push(['Shutter',Math.max(0,d.w-r),Math.max(0,d.h-r),t]);if(/drawer|basket/i.test(k)){parts.push(['Drawer/Basket Front',Math.max(0,d.w-r),Math.max(0,Math.round(d.h/4)-r),t])}return parts.map(x=>({unit:i+1,type:k,part:x[0],length:x[1],width:x[2],thickness:x[3]}))}
let last=[];function gen(){last=[];objs().forEach((o,i)=>last.push(...cutFor(o,i+1)));render();return last}
function render(){let out=document.getElementById('r37out');if(!last.length){out.innerHTML='<div class="r37card">No cabinet objects found. Add units and generate again.</div>';return}let h='<div class="r37card"><b>'+last.length+' panel lines</b><table class="r37table"><tr><th>Unit</th><th>Part</th><th>L</th><th>W</th><th>T</th></tr>';last.slice(0,150).forEach(x=>h+=`<tr><td>${x.unit}</td><td>${x.part}</td><td>${x.length}</td><td>${x.width}</td><td>${x.thickness}</td></tr>`);h+='</table></div>';out.innerHTML=h}
function csv(){if(!last.length)gen();let s='Unit,Type,Part,Length mm,Width mm,Thickness mm\n'+last.map(x=>[x.unit,x.type,x.part,x.length,x.width,x.thickness].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='RR-V37-Cut-List.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.getElementById('r37gen').onclick=gen;document.getElementById('r37csv').onclick=csv;document.getElementById('r37clear').onclick=()=>{last=[];document.getElementById('r37out').innerHTML=''};document.getElementById('r37print').onclick=()=>{if(!last.length)gen();let w=window.open('','_blank');if(!w)return;w.document.write('<html><head><title>RR V37 Cut List</title><style>body{font-family:Arial;padding:25px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #aaa;padding:6px;font-size:11px}</style></head><body><h2>RR 3D Kitchen Planner — V37 Cut List</h2>'+document.getElementById('r37out').innerHTML+'</body></html>');w.document.close();w.print()};
})();
