(function(){
const css=document.createElement('style');css.textContent=`#rrv39{position:fixed;left:14px;top:14px;width:340px;max-height:78vh;overflow:auto;background:rgba(10,14,20,.98);color:#eef2f7;z-index:100001;padding:14px;border:1px solid #526071;border-radius:14px;font:12px Arial;box-shadow:0 14px 45px #0009}#rrv39 h3{margin:0 0 6px;font-size:16px}.r39g{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:6px 0}.r39g>*{min-width:0}.r39in,.r39btn,.r39sel{width:100%;box-sizing:border-box;padding:7px;border-radius:7px;border:1px solid #455262;background:#1c2530;color:#fff}.r39full{grid-column:1/-1}.r39small{font-size:10px;opacity:.72}.r39status{padding:8px;background:#0b1016;border-radius:8px;margin-top:8px;white-space:pre-wrap;line-height:1.35}`;document.head.appendChild(css);
const p=document.createElement('div');p.id='rrv39';p.innerHTML=`<h3>V39 • Project Handover Pack <span style="font-size:9px;background:#22c55e;color:#06120a;padding:3px 6px;border-radius:99px">PRO</span></h3><div class="r39small">Create one clean client/designer handover document from the current 3D project.</div><div class="r39g"><label>Project<input class="r39in" id="r39project" placeholder="RR Kitchen Project"></label><label>Client<input class="r39in" id="r39client" placeholder="Client name"></label><label>Designer<input class="r39in" id="r39designer" placeholder="Designer"></label><label>Revision<input class="r39in" id="r39rev" value="Rev-01"></label><label class="r39full">Notes<textarea class="r39in" id="r39notes" rows="3" placeholder="Site notes / installation notes"></textarea></label><button class="r39btn" id="r39gen">Generate Pack</button><button class="r39btn" id="r39print">Print / Save PDF</button><button class="r39btn" id="r39json">Export JSON</button><button class="r39btn" id="r39csv">Export CSV</button><button class="r39btn r39full" id="r39save">Save Handover Details</button></div><div id="r39status" class="r39status">V39 ready • Generate the project handover pack.</div></div>`;document.body.appendChild(p);
const $=id=>document.getElementById(id);const mm=n=>Math.round(n*1000);function objs(){return (window.objects||[]).filter(o=>o&&o.visible!==false&&o.isObject3D)}
function rows(){return objs().map((o,i)=>{let b=new THREE.Box3().setFromObject(o),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),u=o.userData||{},m=u.rrV32||u.v32||{};return {No:i+1,Name:u.name||o.name||'Object',Category:u.category||u.type||'Model',W:mm(s.x),H:mm(s.y),D:mm(s.z),X:mm(c.x),Y:mm(c.y),Z:mm(c.z),Finish:m.finish||m.material||'',Handle:m.handle||''}})}
function data(){return {project:$('r39project').value||'RR Kitchen Project',client:$('r39client').value||'',designer:$('r39designer').value||'',revision:$('r39rev').value||'Rev-01',notes:$('r39notes').value||'',generatedAt:new Date().toISOString(),objects:rows()}}
function table(a){return '<table><tr><th>#</th><th>Object</th><th>Category</th><th>W×H×D mm</th><th>X/Y/Z mm</th><th>Finish</th><th>Handle</th></tr>'+a.map(x=>`<tr><td>${x.No}</td><td>${x.Name}</td><td>${x.Category}</td><td>${x.W}×${x.H}×${x.D}</td><td>${x.X}/${x.Y}/${x.Z}</td><td>${x.Finish}</td><td>${x.Handle}</td></tr>`).join('')+'</table>'}
function generate(){let d=data();localStorage.setItem('RR_V39_HANDOVER',JSON.stringify(d));$('r39status').textContent=`Handover pack generated.\n${d.objects.length} objects included.\nProject: ${d.project} • ${d.revision}`;return d}
$('r39gen').onclick=generate;$('r39save').onclick=()=>{let d=data();localStorage.setItem('RR_V39_HANDOVER',JSON.stringify(d));$('r39status').textContent='Handover details saved locally.'};
$('r39json').onclick=()=>{let d=generate(),u=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='RR-V39-Handover.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('r39csv').onclick=()=>{let d=generate(),head='No,Name,Category,W mm,H mm,D mm,X mm,Y mm,Z mm,Finish,Handle\n',s=head+d.objects.map(x=>[x.No,x.Name,x.Category,x.W,x.H,x.D,x.X,x.Y,x.Z,x.Finish,x.Handle].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),u=URL.createObjectURL(new Blob([s],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='RR-V39-Handover-Objects.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('r39print').onclick=()=>{let d=generate(),w=window.open('','_blank');if(!w){$('r39status').textContent='Allow pop-ups to print/save PDF';return}w.document.write(`<html><head><title>${d.project} - RR V39 Handover</title><style>@page{size:A4;margin:14mm}body{font:11px Arial;color:#111}h1{font-size:22px;margin-bottom:4px}h2{font-size:15px;margin-top:18px;border-bottom:1px solid #999;padding-bottom:4px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:12px 0}table{border-collapse:collapse;width:100%;font-size:8px}th,td{border:1px solid #aaa;padding:5px;text-align:left}th{background:#eee}.notes{border:1px solid #aaa;padding:10px;min-height:55px;white-space:pre-wrap}.foot{margin-top:20px;font-size:9px;color:#555}</style></head><body><h1>RR 3D Kitchen Planner</h1><div>Project Handover Pack</div><div class="meta"><div><b>Project:</b> ${d.project}</div><div><b>Client:</b> ${d.client}</div><div><b>Designer:</b> ${d.designer}</div><div><b>Revision:</b> ${d.revision}</div></div><h2>3D Object Specification</h2>${table(d.objects)}<h2>Notes</h2><div class="notes">${d.notes||'No additional notes.'}</div><div class="foot">Generated from the current 3D scene. Verify site dimensions, wall conditions, services, hardware and final manufacturing dimensions before execution.</div></body></html>`);w.document.close();w.focus();w.print()};
try{let d=JSON.parse(localStorage.getItem('RR_V39_HANDOVER')||'null');if(d){$('r39project').value=d.project||'';$('r39client').value=d.client||'';$('r39designer').value=d.designer||'';$('r39rev').value=d.revision||'Rev-01';$('r39notes').value=d.notes||'';$('r39status').textContent='Saved handover details loaded locally.'}}catch(e){}
})();
